Feature: VisualEditor on production wikis

  Verify that VisualEditor is available as
  expected on production wiki sites.

  Exclusions (see Bugzilla 60842):

  http://af.wikipedia.org
  http://am.wikipedia.org
  http://bpy.wikipedia.org
  http://cv.wikipedia.org
  http://kaa.wikipedia.org
  http://ln.wikipedia.org
  http://mzn.wikipedia.org
  http://new.wikipedia.org
  http://pt.wikiversity.org
  http://szl.wikipedia.org

  Scenario Outline: VisualEditor production availability
    Given I visit a non-existent page at <wiki>
    Then I should see the Visual Editor editing surface
  Examples:
    | wiki                 |
    | www.mediawiki.org    |
    | pt.wikibooks.org     |
    | se.wikimedia.org     |
    | test.wikipedia.org   |
    | test2.wikipedia.org  |
    | aa.wikipedia.org     |
    | ab.wikipedia.org     |
    | ace.wikipedia.org    |
    | ak.wikipedia.org     |
    | als.wikipedia.org    |
    | ang.wikipedia.org    |
    | an.wikipedia.org     |
    | arc.wikipedia.org    |
    | ar.wikipedia.org     |
    | arz.wikipedia.org    |
    | ast.wikipedia.org    |
    | as.wikipedia.org     |
    | av.wikipedia.org     |
    | ay.wikipedia.org     |
    | az.wikipedia.org     |
    | bar.wikipedia.org    |
    | ba.wikipedia.org     |
    | bcl.wikipedia.org    |
    | be.wikipedia.org     |
    | bg.wikipedia.org     |
    | bh.wikipedia.org     |
    | bi.wikipedia.org     |
    | bjn.wikipedia.org    |
    | bm.wikipedia.org     |
    | bn.wikipedia.org     |
    | bo.wikipedia.org     |
    | br.wikipedia.org     |
    | bs.wikipedia.org     |
    | bug.wikipedia.org    |
    | bxr.wikipedia.org    |
    | ca.wikipedia.org     |
    | cdo.wikipedia.org    |
    | ceb.wikipedia.org    |
    | ce.wikipedia.org     |
    | cho.wikipedia.org    |
    | chr.wikipedia.org    |
    | ch.wikipedia.org     |
    | chy.wikipedia.org    |
    | ckb.wikipedia.org    |
    | co.wikipedia.org     |
    | crh.wikipedia.org    |
    | cr.wikipedia.org     |
    | csb.wikipedia.org    |
    | cs.wikipedia.org     |
    | cu.wikipedia.org     |
    | cy.wikipedia.org     |
    | da.wikipedia.org     |
    | de.wikipedia.org     |
    | diq.wikipedia.org    |
    | dsb.wikipedia.org    |
    | dv.wikipedia.org     |
    | dz.wikipedia.org     |
    | ee.wikipedia.org     |
    | el.wikipedia.org     |
    | eml.wikipedia.org    |
    | en.wikipedia.org     |
    | eo.wikipedia.org     |
    | es.wikipedia.org     |
    | et.wikipedia.org     |
    | eu.wikipedia.org     |
    | ext.wikipedia.org    |
    | fa.wikipedia.org     |
    | ff.wikipedia.org     |
    | fi.wikipedia.org     |
    | fj.wikipedia.org     |
    | fo.wikipedia.org     |
    | frp.wikipedia.org    |
    | frr.wikipedia.org    |
    | fr.wikipedia.org     |
    | fur.wikipedia.org    |
    | fy.wikipedia.org     |
    | gag.wikipedia.org    |
    | gan.wikipedia.org    |
    | ga.wikipedia.org     |
    | gd.wikipedia.org     |
    | glk.wikipedia.org    |
    | gl.wikipedia.org     |
    | gn.wikipedia.org     |
    | got.wikipedia.org    |
    | gu.wikipedia.org     |
    | gv.wikipedia.org     |
    | hak.wikipedia.org    |
    | ha.wikipedia.org     |
    | haw.wikipedia.org    |
    | he.wikipedia.org     |
    | hif.wikipedia.org    |
    | hi.wikipedia.org     |
    | ho.wikipedia.org     |
    | hr.wikipedia.org     |
    | hsb.wikipedia.org    |
    | ht.wikipedia.org     |
    | hu.wikipedia.org     |
    | hy.wikipedia.org     |
    | hz.wikipedia.org     |
    | ia.wikipedia.org     |
    | id.wikipedia.org     |
    | ie.wikipedia.org     |
    | ig.wikipedia.org     |
    | ii.wikipedia.org     |
    | ik.wikipedia.org     |
    | ilo.wikipedia.org    |
    | io.wikipedia.org     |
    | is.wikipedia.org     |
    | it.wikipedia.org     |
    | iu.wikipedia.org     |
    | ja.wikipedia.org     |
    | jbo.wikipedia.org    |
    | jv.wikipedia.org     |
    | kab.wikipedia.org    |
    | ka.wikipedia.org     |
    | kbd.wikipedia.org    |
    | kg.wikipedia.org     |
    | ki.wikipedia.org     |
    | kj.wikipedia.org     |
    | kk.wikipedia.org     |
    | kl.wikipedia.org     |
    | km.wikipedia.org     |
    | kn.wikipedia.org     |
    | koi.wikipedia.org    |
    | ko.wikipedia.org     |
    | krc.wikipedia.org    |
    | kr.wikipedia.org     |
    | ksh.wikipedia.org    |
    | ks.wikipedia.org     |
    | ku.wikipedia.org     |
    | kv.wikipedia.org     |
    | kw.wikipedia.org     |
    | ky.wikipedia.org     |
    | lad.wikipedia.org    |
    | la.wikipedia.org     |
    | lbe.wikipedia.org    |
    | lb.wikipedia.org     |
    | lez.wikipedia.org    |
    | lg.wikipedia.org     |
    | lij.wikipedia.org    |
    | li.wikipedia.org     |
    | lmo.wikipedia.org    |
    | lo.wikipedia.org     |
    | ltg.wikipedia.org    |
    | lt.wikipedia.org     |
    | lv.wikipedia.org     |
    | mdf.wikipedia.org    |
    | mg.wikipedia.org     |
    | mhr.wikipedia.org    |
    | mh.wikipedia.org     |
    | min.wikipedia.org    |
    | mi.wikipedia.org     |
    | mk.wikipedia.org     |
    | ml.wikipedia.org     |
    | mn.wikipedia.org     |
    | mo.wikipedia.org     |
    | mrj.wikipedia.org    |
    | mr.wikipedia.org     |
    | ms.wikipedia.org     |
    | mt.wikipedia.org     |
    | mus.wikipedia.org    |
    | mwl.wikipedia.org    |
    | myv.wikipedia.org    |
    | nah.wikipedia.org    |
    | nap.wikipedia.org    |
    | na.wikipedia.org     |
    | nds.wikipedia.org    |
    | ne.wikipedia.org     |
    | ng.wikipedia.org     |
    | nl.wikipedia.org     |
    | nn.wikipedia.org     |
    | nov.wikipedia.org    |
    | no.wikipedia.org     |
    | nrm.wikipedia.org    |
    | nso.wikipedia.org    |
    | nv.wikipedia.org     |
    | ny.wikipedia.org     |
    | oc.wikipedia.org     |
    | om.wikipedia.org     |
    | or.wikipedia.org     |
    | os.wikipedia.org     |
    | pag.wikipedia.org    |
    | pam.wikipedia.org    |
    | pap.wikipedia.org    |
    | pa.wikipedia.org     |
    | pcd.wikipedia.org    |
    | pdc.wikipedia.org    |
    | pfl.wikipedia.org    |
    | pih.wikipedia.org    |
    | pi.wikipedia.org     |
    | pl.wikipedia.org     |
    | pms.wikipedia.org    |
    | pnb.wikipedia.org    |
    | pnt.wikipedia.org    |
    | ps.wikipedia.org     |
    | pt.wikipedia.org     |
    | qu.wikipedia.org     |
    | rm.wikipedia.org     |
    | rmy.wikipedia.org    |
    | rn.wikipedia.org     |
    | ro.wikipedia.org     |
    | rue.wikipedia.org    |
    | ru.wikipedia.org     |
    | rw.wikipedia.org     |
    | sah.wikipedia.org    |
    | sa.wikipedia.org     |
    | scn.wikipedia.org    |
    | sco.wikipedia.org    |
    | sc.wikipedia.org     |
    | sd.wikipedia.org     |
    | se.wikipedia.org     |
    | sg.wikipedia.org     |
    | sh.wikipedia.org     |
    | simple.wikipedia.org |
    | si.wikipedia.org     |
    | sk.wikipedia.org     |
    | sl.wikipedia.org     |
    | sm.wikipedia.org     |
    | sn.wikipedia.org     |
    | so.wikipedia.org     |
    | sq.wikipedia.org     |
    | srn.wikipedia.org    |
    | sr.wikipedia.org     |
    | ss.wikipedia.org     |
    | stq.wikipedia.org    |
    | st.wikipedia.org     |
    | su.wikipedia.org     |
    | sv.wikipedia.org     |
    | sw.wikipedia.org     |
    | ta.wikipedia.org     |
    | tet.wikipedia.org    |
    | te.wikipedia.org     |
    | tg.wikipedia.org     |
    | th.wikipedia.org     |
    | ti.wikipedia.org     |
    | tk.wikipedia.org     |
    | tl.wikipedia.org     |
    | tn.wikipedia.org     |
    | to.wikipedia.org     |
    | tpi.wikipedia.org    |
    | tr.wikipedia.org     |
    | ts.wikipedia.org     |
    | tt.wikipedia.org     |
    | tum.wikipedia.org    |
    | tw.wikipedia.org     |
    | ty.wikipedia.org     |
    | tyv.wikipedia.org    |
    | udm.wikipedia.org    |
    | ug.wikipedia.org     |
    | uk.wikipedia.org     |
    | ur.wikipedia.org     |
    | uz.wikipedia.org     |
    | vec.wikipedia.org    |
    | vep.wikipedia.org    |
    | ve.wikipedia.org     |
    | vi.wikipedia.org     |
    | vls.wikipedia.org    |
    | vo.wikipedia.org     |
    | war.wikipedia.org    |
    | wa.wikipedia.org     |
    | wo.wikipedia.org     |
    | wuu.wikipedia.org    |
    | xal.wikipedia.org    |
    | xh.wikipedia.org     |
    | xmf.wikipedia.org    |
    | yi.wikipedia.org     |
    | yo.wikipedia.org     |
    | za.wikipedia.org     |
    | zea.wikipedia.org    |
    | zh.wikipedia.org     |
    | zu.wikipedia.org     |
